<?php

/**
 * @file
 * Test module used for providing hook implementation used in tests.
 *
 * Test hooks alter content only if the test mode is enabled ('test_mode'
 * variable is set).
 * This module should never be enabled in production.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Messenger\MessengerInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;
use Drupal\testmate\Testmate;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_query_alter().
 */
function testmate_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  // Add cache tag to all views.
  // Required to invalidate tags when enabling test mode for already cached
  // views.
  // Since this module is not for production environment, the views caching
  // may be reset more often, so using single views tag for all views is
  // sufficient enough.
  $view->element['#cache']['tags'][] = Testmate::CACHE_VIEWS;

  $testmate = Testmate::getInstance();
  if ($testmate->isTestMode()) {
    if (in_array($view->id(), $testmate->getNodeViews())) {
      if (!in_array('title', array_keys($query->fields))) {
        $query->addField('node_field_data', 'title');
      }
      $query->addWhere(0, 'node_field_data.title', $testmate->getNodePattern(), 'LIKE');
      return;
    }

    if (in_array($view->id(), $testmate->getTermViews())) {
      if (!in_array('name', array_keys($query->fields))) {
        $query->addField('taxonomy_term_field_data', 'name');
      }
      $query->addWhere(0, 'taxonomy_term_field_data.name', $testmate->getTermPattern(), 'LIKE');
      return;
    }

    if (in_array($view->id(), $testmate->getUserViews())) {
      if (!in_array('mail', array_keys($query->fields))) {
        $query->addField('users_field_data', 'mail');
      }
      $query->addWhere(0, 'users_field_data.mail', $testmate->getUserPattern(), 'LIKE');
      return;
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function testmate_form_taxonomy_overview_terms_alter(&$form, FormStateInterface $form_state, $form_id) {
  $testmate = Testmate::getInstance();
  // Remove terms from the Taxonomy Term Overview page.
  if ($testmate->isTestMode()) {
    if ($testmate->getListTerm()) {
      foreach (Element::children($form['terms']) as $field) {
        if (!Testmate::matchLike($testmate->getTermPattern(), $form['terms'][$field]['term']['#title'])) {
          unset($form['terms'][$field]);
        }
      }
    }
  }
}

/**
 * Implements hook_page_bottom().
 */
function testmate_page_bottom(array &$page_bottom) {
  if (\Drupal::currentUser()->hasPermission('administer site configuration') && Testmate::getInstance()->isTestMode()) {
    $messenger = \Drupal::messenger();
    $link = Link::fromTextAndUrl(t('Testmate config page'), Url::fromRoute('testmate.admin_settings'))->toString();
    $messenger->addMessage(t('Test mode is enabled. Most likely your tests did not clear the test mode flag properly. Disable test mode at @link.', ['@link' => $link]), MessengerInterface::TYPE_WARNING);
  }
}
